apiVersion: v1
kind: Service
metadata:
  name: resource-text-indexer
  namespace: resource-text-indexer
  labels:
    app.kubernetes.io/name: resource-text-indexer
spec:
  selector:
    app.kubernetes.io/name: resource-text-indexer
  ports:
    - name: http
      port: 80
      targetPort: http
